all: client server echo echoClient

client: client.c
	gcc -o client client.c -Wall -Werror

server: server.c
	gcc -o server server.c -Wall -Werror

echoClient: echoClient.c
	gcc -o echoClient echoClient.c -Wall -Werror